name: Build and deploy of EventMark v1

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean install

      - name: Run all tests
        run: mvn test

      - name: Build Artifact
        run: mvn clean package

      - name: Store Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-jar
          path: target/*.jar