name: Build and deploy of EventMark v1

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean install

      - name: Run all tests
        run: mvn test

      - name: Build Artifact
        run: mvn clean package

      - name: Store Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-jar
          path: target/*.jar

      - name: Config SSH and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          scp -o StrictHostKeyChecking=no target/EventMark-0.0.1-SNAPSHOT.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/EventMark.jar

          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "
          pm2 delete eventmark || true
          pm2 start 'java -jar /home/ec2-user/EventMark.jar' --name eventmark
          "