name: Build and deploy of EventMark v1

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean install

      - name: Run all tests
        run: mvn test

      - name: Build Artifact
        run: mvn clean package

      - name: Store Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-jar
          path: target/*.jar

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp-jar
          path: target/

      - name: Configurar SSH e Deploy
        run: |
                scp -i ${{ secrets.SSH_PRIVATE_KEY }} target/myapp-*.jar ec2-user@${{ secrets.EC2_USER }}:/app/myapp.jar
                ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_USER }} "sudo systemctl restart myapp-java-service"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
