name: Build and deploy of EventMark v1

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean install

      - name: Run all tests
        run: mvn test

      - name: Build Artifact
        run: mvn clean package

      - name: Store Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-jar
          path: target/*.jar

      - name: Config SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-232-61-205.compute-1.amazonaws.com "cd /app && git pull && npm install && pm2 restart app"
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}