deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: myapp-jar
        path: target/

    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa target/myapp-*.jar ec2-user@${{ secrets.EC2_HOST }}:/app/myapp.jar
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} "sudo systemctl restart myapp-java-service"